import Layout from '@/components/Layout';
import ProjectCard from '@/components/ProjectCard';
import Head from 'next/head';

export default function Home({projects}) {

  return (
    <>
      <Head>
        <title>deverholzer - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <div className="main-content">
            <section className="side-projects">
              <h3>Some of my side projects</h3>

              <div className="project-list">
                {
                  projects.map(project => 
                    <ProjectCard 
                      project={project}
                      key={project.id}
                    />
                  )
                }
              </div>
            </section>
          </div>
        </main>
      </Layout>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/projects");
  const projects = await res.json();

  return {
    props: {
      projects
    }
  }
}
