import Layout from '@/components/Layout';
import ProjectCard from '@/components/ProjectCard';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>deverholzer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <div class="main-content">
            <section class="side-projects">
              <h3>Some of my side projects</h3>

              <div class="project-list">

                <ProjectCard />
              </div>
            </section>
          </div>
        </main>
      </Layout>
    </>
  )
}
